# Generated by Django 3.2.2 on 2021-06-11 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracking_app', '0002_remove_contributor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
